sequenceDiagram
    participant browser
    participant server
    browser->>server: Post https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    Note right of server: server writes this to memory
    server-->>browser: {"message":"note created"}
